version: '3'

services:
  discordbot:
    container_name: discord-bot
    # image: vatsca/python:latest
    build: .
    command: ["python", "bot.py"]
    restart: unless-stopped
    volumes:
      - ./:/app
    network_mode: host
