version: '3'

services:
  discordbot:
    container_name: discord-bot
    image: vatsca/python:latest
    command: bash -c "pip3 install -r requirements.txt && python3 bot.py"
    volumes:
      - ./:/app
    network_mode: host